### PR TITLE
Added kernel path

### PR DESCRIPTION
**Pull request by chdlc**
kernel not found during build

### CODE REVIEW

**Comment by iamimmanuelraj** [comment]
@chdelacr Change clang version

**Comment by ghost** [comment]
https://github.com/xiaomi-sdm660/android_device_xiaomi_jasmine_sprout/blob/eleven/BoardConfig.mk#L43

**Comment by pix106** [comment]
It's defined in device, not in common

**Comment by chdlc** [comment]
Got it, it's a common path anyway, but I get it. Thanks everyone

**Pull request closed without merging**
